AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'unlocode.gemspec'
    - 'unlocodes.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'lib/unlocodes/coordinates.rb'
    - 'lib/unlocodes/registry.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/unlocodes/registry.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/unlocodes/registry.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes